# Generated by Django 5.1.1 on 2024-09-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyreels', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('user_info', models.CharField(max_length=255)),
                ('transcribation', models.TextField()),
                ('rewriting', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
